server:
  port: 8080

spring:
  application:
    name: jasmine-gateway
  profiles:
    default: dev
  config:
    import:
      - nacos:jasmine-common.yml?refresh=true
      - nacos:jasmine-gateway.yml?refresh=true
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        namespace: ${NACOS_NAMESPACE:dev}
        group: JASMINE
      config:
        namespace: ${NACOS_NAMESPACE:dev}
        group: JASMINE

logging:
  level:
    com.nfu.jasmine: INFO
