server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: jasmine-gateway
  profiles:
    default: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s
  config:
    import:
      - optional:nacos:jasmine-observability.yml?refresh=true
      - optional:nacos:jasmine-redis-common.yml?refresh=true
      - optional:nacos:jasmine-gateway.yml?refresh=true
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:}
      password: ${NACOS_PASSWORD:}
      discovery:
        namespace: ${NACOS_NAMESPACE:dev}
        group: JASMINE
      config:
        namespace: ${NACOS_NAMESPACE:dev}
        group: JASMINE

logging:
  level:
    com.nfu.jasmine: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
