server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # 针对 Vue 历史模式路由的支持，由于目前的架构是 hash，这句能起到很好的降级防御作用
        try_files $uri $uri/ /index.html;
    }

    # 反向代理：把前端代码里发起的前缀为 /prod-api/ 的请求，全部转发给后端节点
    location /prod-api/ {
        # 'backend' 是 docker-compose.yml 里面定义的服务名称，Nginx 会自动执行内网 DNS 解析找到它
        # 注意这里的末尾有 / ，表示会自动将 /prod-api/ 前缀剔除，转而访问后端真实路径 http://backend:9999/xxx
        proxy_pass http://backend:9999/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
